### ISSUE TITLE
Add a default tweet message that advertises the website

### ISSUE THREAD

**Issue by yogodoshi** [yogodoshi/cansei#21]
It will be a way to advertise the website, to gather more people that hates the given company to sign up and start tweeting as well!

Maybe we should hardcode the message in the code so people can't easily remove it from the yaml file? Nothing like a shady thing but because I think most people will just remove all the messages without reading them.

Another option would be creating a new key in the settings just for this message which would allow people to easily change it 🤔

**Comment by nicknish** [comment]
> Another option would be creating a new key in the settings just for this message

Yup. Suggestion: `preview_message`?

**Comment by yogodoshi** [comment]
Hmm I think that "preview message" sounds like a fake message that wouldn't be sent. I couldn't think of a good name now though :(

**Comment by nicknish** [comment]
`message_sample` or `featured_message`?

**Comment by yogodoshi** [comment]
Sample still looks like an "example" which might not be used, `featured_message` is the best one so far IMO 👍

**Comment by nicknish** [comment]
I can implement this. Any thought to where it will go in the design? See #17 for mocks

**Comment by yogodoshi** [comment]
Hmmm I think there is a confusion going on here, what I meant in this issue is to just hardcode a random tweet in the tweet list. It would appear only in the settings file, not in the UI. A new key with a tweet message as its value, like: "If you also are fed up with the terrible service that Santander is delivering, join us: http://santanderhasterribleservice.com".

And `TwitterService#random_complain_message` would get a random message from the sum of the random tweets + this "featured_message".

This what was I wanted to discuss in this issue. What I think you understood is like showing in the UI an example of a tweet, isn't it? I think we talked about this on slack... which I also think its good to have! Maybe create a new issue for it?
