### ISSUE TITLE
Design and add favicon

### ISSUE THREAD

**Issue by nicknish** [yogodoshi/cansei#22]

**Comment by nicknish** [comment]
@yogodoshi any thoughts man!

**Comment by yogodoshi** [comment]
Hmmm I like the idea of a favicon but gotta be something abstract around the "Im pissed" idea, right? But we can also make it configurable and explain how to change it in the README.

**Comment by nicknish** [comment]
Yes, definitely gotta be around the "tired" or "I'm pissed" idea. Can also be global (like an emoji) just in case people clone this and want to just get started

**Comment by nicknish** [comment]
some suggestions: 👊 ✊ 😠 😡 💢 👎

**Comment by yogodoshi** [comment]
Nice idea, I like the third and fourth one the most :)
