### ISSUE TITLE
Set codeclimate up

### ISSUE THREAD

**Issue by maurogeorge** [yogodoshi/cansei#26]
https://codeclimate.com/

With this set up, I think we can close the https://github.com/yogodoshi/cansei/issues/10, since the codeclimate also provides test coverage.

**Comment by yogodoshi** [comment]
Hmm I just set Travis up: #20 

Do you think Code Climate is better than Travis to justify replacing it? Cause I think adding coveralls should be easier now.

**Comment by maurogeorge** [comment]
No no, I think they can live together Travis will run your specs. Codeclimate will look for the quality of your codebase https://codeclimate.com/product.

But if you think does not make sense, feel free to close 😄
